name: run tests cases on push

on :
    push:
        branches:
            - main

jobs:
        build:
            runs-on: ubuntu-latest
            steps:
                - uses: actions/checkout@v2
                - name: Set up nextjs
                  uses: actions/setup-node@v2
                  with:
                    node-version: '16'
                - name: Install dependencies
                  run: |
                    npm install
                - name: build app
                  run: |
                    npm run build